id: I05540C5C
ocr_import_info:
  timestamp: '2023-08-21T07:20:12.630840+00:00'
  batch_id: batch-142c
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Tenzin Jordhen
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-08-21 07:39:10.784139+00:00
last_modified: 2023-08-21 07:39:10.784145+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG550
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG550
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སེ་ར་བྱེས་ཀྱི་དབུ་མའི་ཡིག་ཆ།
  languages:
  - bo
  author: སེ་ར་རྗེ་བཙུན་ཆོས་ཀྱི་རྒྱལ་མཚན།
statistics:
  ocr_word_mean_confidence_index: 0.9681242192762907
  ocr_word_median_confidence_index: 0.99965835
bases:
  I1KG552:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG552
      total_pages: 656
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG552.txt
    statistics:
      ocr_word_median_confidence_index: 0.99965835
      ocr_word_mean_confidence_index: 0.9681242192762907
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
